on Foo pParam
   -- code
end Foo

command Foo pParam
   -- code
end Foo

private command Foo pParam
   -- code
end Foo

private on Foo pParam
   -- code
end Foo

before Foo pParam
   -- code
end Foo

after Foo pParam
   -- code
end Foo

function Foo pParam
   -- code
end Foo

private function Foo pParam
   -- code
end Foo

setProp Foo pParam
   -- code
end Foo

getProp Foo pParam
   -- code
end Foo
