on foo
   if foo() then
      -- code
   else if bar() then
      -- code
   else
      -- code
   end if
   -- comment
end foo

on foo
   if foo()
   then -- code
   else if bar() then
      -- code
   else
      -- code
   end if
   -- comment
end foo

on foo
   if foo()
   then code
   else if bar() then
      -- code
   else code
   -- comment
end foo

on foo
   if foo()
   then code
   else code
   -- comment
end foo

on foo
   if foo() then code else code
   -- comment
end foo

on foo
   if foo() then 
      if bar() then code else code
   else 
      code 
   end if
   -- comment
end foo

on foo
   if foo() then
      if bar() then code
      else
         code
      end if
   end if
   -- comment
end foo

on foo
   if foo()
   then code else code
   -- comment
end foo

on foo
   if foo() 
   then 
      code else code
   -- comment
end foo

on foo
   if foo() then 
      code else code
   -- comment
end foo
