repeat forever
   -- code
end repeat

repeat while foo()
   -- code
end repeat

repeat until foo()
   -- code
end repeat

repeat 3
   -- code
end repeat

repeat for 3
   -- code
end repeat

repeat for 3 times
   -- code
end repeat

repeat 3 times
   -- code
end repeat

repeat with X = 1 to 5
   -- code
end repeat

repeat with X = 1 to 5 step 2
   -- code
end repeat

repeat with X = 5 down to 1
   -- code
end repeat

repeat with X = 5 down to 1 step 2
   -- code
end repeat

repeat for each line tLine in tFoo
   -- code
end repeat
