on foo
   repeat forever
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat while foo()
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat until foo()
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat 3
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat for 3
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat for 3 times
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat 3 times
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat with X = 1 to 5
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat with X = 1 to 5 step 2
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat with X = 5 down to 1
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat with X = 5 down to 1 step 2
      -- code
   end repeat
   -- comment
end foo

on foo
   repeat for each line tLine in tFoo
      -- code
   end repeat
   -- comment
end foo
