script "RevDataGridLibraryBehaviorsDgListMessageCatcherButtonBehavior"
-- Catch messages sent to instances of templates
-- This insulates the outside world from these internal messages
on FillInData
    
end FillInData
    
    
on PreFillInData
    
end PreFillInData


on ResetData
    
end ResetData
    
    
on LayoutControl
    
end LayoutControl
    
    
setprop dgHilite
     
end dgHilite
     
     
getprop dgDataControl
   
end dgDataControl
    
